title: Max Planck Institute for Biological Intelligence 
logo: /assets/img/logo.png 
description: Reporting links
qr-code: /assets/img/qr-code.png 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
